### PR TITLE
Fix grammatical errors

### PR DESCRIPTION
**Pull request by archisha69**
fixed a bunch of (grammar and much more) mistakes
fixed monthly cmd wrong msg output ("weekly")
debloated with f string
smoothened descriptions of slashies

### CODE REVIEW

**Comment by notsniped** [comment]
I will have to check the new slash command descriptions, just give me a moment

**Comment by notsniped** [comment]
### Line 286 & 313
There are those few people who deposit or withdraw 1 coin. So it would still be grammatically incorrect to change it to "coins".
I will fond a workaround for it.

**Comment by notsniped** [comment]
> ### Line 286 & 313
> 
> There are those few people who deposit or withdraw 1 coin. So it would still be grammatically incorrect to change it to "coins". I will fond a workaround for it.

I think i need to fix my eyes, that was already provided in pr

**Comment by archisha69** [comment]
> > ### Line 286 & 313
> > There are those few people who deposit or withdraw 1 coin. So it would still be grammatically incorrect to change it to "coins". I will fond a workaround for it.
> 
> I think i need to fix my eyes, that was already provided in pr

LLLLLLLLL

**Review by notsniped — APPROVED** [review]
### PR Review Complete
All grammatical errors and descriptions have been fixed! This is now ready for merge.

**Comment by notsniped** [comment]
Thanks for the grammatical support olo

**Pull request merged**
